import { formatDateline } from "@/lib/format";
import { tierLabel } from "@/lib/families";
import type { ImportanceTier } from "@/lib/types";

interface DigestHeaderProps {
  kicker: string; // e.g. "Daily Digest" / "Week at a Glance"
  title: string; // the TL;DR or weekly headline
  date: string; // ISO date for the dateline
  tier?: ImportanceTier;
  quiet?: boolean;
  model?: string;
}

/**
 * The masthead: a mono dateline + kicker over a large serif headline, ruled off
 * with a hairline. Retro newspaper feel; accent reserved for the tier badge.
 */
export function DigestHeader({
  kicker,
  title,
  date,
  tier,
  quiet,
  model,
}: DigestHeaderProps): JSX.Element {
  return (
    <header className="mb-8 border-b border-hairline pb-6">
      <div className="flex flex-wrap items-center gap-x-3 gap-y-1">
        <p className="label-mono text-accent">{kicker}</p>
        <span aria-hidden className="text-hairline">
          ·
        </span>
        <time className="label-mono" dateTime={date}>
          {formatDateline(date)}
        </time>
        {tier ? (
          <span
            className={[
              "label-mono rounded-full border px-2 py-0.5",
              quiet || tier === "quiet_day"
                ? "border-hairline text-muted"
                : tier === "breakthrough"
                  ? "border-accent text-accent"
                  : "border-hairline text-ink/70",
            ].join(" ")}
          >
            {tierLabel(tier)}
          </span>
        ) : null}
      </div>

      <h1 className="mt-3 font-serif text-3xl font-bold leading-tight tracking-tight sm:text-4xl">
        {title}
      </h1>

      {model ? (
        <p className="label-mono mt-3 text-muted">
          generated by <span className="text-ink/70">{model}</span>
        </p>
      ) : null}
    </header>
  );
}
